
The speech children hear mentions more atypical than typical features. Depending on children's pragmatic abilities, this input could provide helpful information or pose a misleading challenge as children learn about the world. If children are able to make the contrastive inference that description tends to pick out atypical features, they could use description to go beyond learning about what they directly experience. If, on the other hand, they merely associate the mentioned feature with the mentioned category, they may mistakenly learn that atypical features are more common than they actually are.

In general, children's pragmatic abilities are thought to undergo prolonged development, not reaching adult-like performance until well into schooling age. The most thoroughly studied pragmatic inference in children, scalar implicature, tells a bleak story about children's ability to make pragmatic inferences at a young age. Scalar implicature is the phenomenon in which use of a weak scalar term ('some,' 'might') implies that a stronger scalar term ('all,' 'must') is not true---for example, "I ate some of the cookies" implies I did not eat all of them. This inference can be derived by reasoning that had the speaker meant the stronger meaning, they would have used the stronger term. Adults consistently interpret the word 'some' to mean 'some but not all,' rating the use of 'some' as unnatural when 'all' is applicable and taking longer to respond to such instances [@bott_utterances_2004; @degen_processing_2015]. Until at least the age of 5 and in some tasks up to 10 years old, children fail to limit the use of 'some' in this way, accepting 'some' as a descriptor when 'all' is true [@noveck_when_2001; @papafragou_scalar_2003]. This deficit is found in a range of measures, from acceptability judgments to eye-tracking [@huang_semantic_2009]. Later work has found that children likely lack this ability because they fail to activate alternative descriptions, so cannot reason that the speaker should have said 'all' and not 'some' if all is true [@barner_accessing_2011], and because they lack a meta-understanding of these tasks [@papafragou_scalar_2003]. When given supportive context, like named alternatives or training on the task, 4- and 5-year-olds improve at these implicatures [@barner_accessing_2011; @papafragou_scalar_2003; @foppolo_scalar_2012]. However, across experiments, performance on scalar implicature remains fragile well into school age.

Contrastive inference from description, however, may be a more accessible form of pragmatic inference because the relevant alternatives are more easily accessible. In the case of using contrastive inference to resolve reference (e.g., "the tall..." prompts looking to a tall object with a shorter counterpart), the relevant alternatives are available in the environment. By the age of 5, children can use contrastive inferences to direct their attention among familiar present objects [@huangsnedeker2008], and when given extra time to orient to the referent, show budding abilities by the age of 3 [@davies_three-year-olds_2021]. Description paired with other contrastive cues can allow children to restrict reference among novel objects or objects with novel properties, though imperfectly [@gelman_implicit_1985; @diesendruck_childrens_2006]. What about when the contrasting set is not available in the environment, but is the referent's category? Preliminary evidence also suggests that contrastive inference about typicality may be possible for young children. When paired with other contrastive cues such as prosody, 4-year-olds can make inferences about novel object typicality, reasoning that "the TALL zib" suggests other zibs are generally shorter [@horowitz_childrens_2016].

In this chapter, we will test children's abilities to make contrastive inferences about typicality. To do this, we will use a task similar to those done by adults in Chapter 2, having children observe novel categories and make inferences about the typicality of their features. We will test children's inferences in two domains: novel concrete objects and novel social groups. Social groups are a particularly interesting testing ground for this inference because we often lack enough direct evidence to make firm inferences about them, yet do hold strong beliefs about their features that likely derive largely from the way people talk about them [@rhodes2012]. Further, if people make contrastive inferences from description about social groups, attempts to counteract a stereotype may inadvertently strengthen it: intentionally mentioning a *positive* feature of a group member may lead to a *negative* inference about the rest of the group [analogous to the inadvertent stereotypes conveyed by comparative phrases, @chestnut_just_2021]. Testing contrastive inference in both of these domains will allow us to generalize our understanding of contrastive inference to a domain in which people's (mis)beliefs about typicality have serious consequences. Comparing children's inferences about novel objects and novel social groups can further help us understand how children weigh different types of evidence in learning about different domains of knowledge.

## Method

### Participants.

We will recruit 60 children ages 4-7 years old, aiming for 15 children per yearly age bin. 

### Design and Procedure.

Children will participate in a storybook-style task in which they observe novel objects and people and make inferences about them. The experiment will have two phases, one about novel fruit objects and one about novel social groups. Half of trials will include just a noun, and half will include an adjective-noun phrase describing the referent. The order of the phases will be randomized, as will the pairing of particular objects to features and the use of an adjective in the trial.

In novel object trials, children will observe a novel object and one of its features will be mentioned (or go unmentioned): "Look at the [tall] toma." The possible features will be tall, wide, spotted, furry, bright, and round. After the observation and utterance, children will see a four-point scale along which the same kind of object varies on the relevant feature, and on which the observed object would fall in the middle. Children will be asked, e.g., "What do you think most tomas look like?" Each trial will use a different object type and novel name.

In novel social group trials, children will see a group member and an image depicting one of its behaviors. The behavior will be described and a feature will be mentioned or go unmentioned: "Look at the [helpful] hibble. He cleaned up this many toys after playtime." Here, the behavior is mentioned in the utterance because it is more difficult to directly observe such actions in an image. The possible features will be helpful (amount of toys cleaned), hungry (number of pancakes eaten), smart (complexity of puzzle solved), strong (size of rock lifted), kind (amount of candy shared), curious (number of books checked out), and brave (size of tree climbed). After observing the individual, children will see a four-point scale along which the depicted behavior varies, and on which the individual's behavior would fall in the middle. Children will be asked, e.g., "How many toys do you think most hibbles would clean up?" All trials will use the same social group, hibbles, with different individuals depicted on each trial and gendered pronouns randomized.

## Analysis

Our key question is whether children make different inferences when a feature is mentioned in the utterance than when it is not. To test this question, we will use an ordinal logistic regression with children's feature choices as the outcome and utterance type (adjective noun vs. noun), trait type, age, and a random intercept by subject as predictors. Data from the novel object phase and the novel social group phase will first be analyzed separately. In order to compare children's inferences about novel objects and social groups, we will then analyze the two phases of the experiment together, with category domain, utterance type, and age as predictors, as well as the interaction between those factors. While interpreting the difference between object and social group inferences is preliminary because the experiment designs are not perfectly comparable, we can examine whether children make stronger inferences in either domain and whether inferences in each domain have different developmental trajectories as an initial step toward understanding how children weigh contrastive inference in their learning over development.

## Discussion

In this chapter, we ask how children develop the inference that that when a feature of a novel category is mentioned, that feature is likely to be atypical of the category. One possibility is that children simply associate the words, features and categories that are salient in an instance of reference. This would lead children to think a mentioned feature is representative or typical of the mentioned category, and given the input children hear, would be misleading. Another possibility is that children make the kind of contrastive inference adults make, inferring that the mentioned feature is atypical. Given prior work on children's development of pragmatic inference, we predict that the youngest children in our sample will make a more associative inference, and that over development children will come to make the contrastive inference more strongly. Given our finding that parents mention atypical features more than typical ones (Chapter 1) and our characterization of adults' contrastive inferences (Chapter 2), the results of this experiment can tell us how children come to make adult-like contrastive inferences and what they might learn from the selective description they hear. 
